Repository openthread/ot-esp32, pull requests merged in 2020-06, with the labels that each got.

#8 [docs] add note to clone the repository and fetch submodules
  example/README.md
Labels: documentation

#9 [uart] fix UART line-ending
  example/README.md
  src/spinel_hdlc.cpp
  src/uart.c
Labels: enhancement

#10 [docs] update ESP-IDF setting up
  example/README.md
Labels: documentation, enhancement
